import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';
import ProtectedAction from './ProtectedAction';
import { callAPI, ApiActions, fileToBase64 } from '../api';
import ItemForm from './ItemForm';

export default function Upload() {
    const navigate = useNavigate();
    const { user } = useAuth();
    const [selectedFile, setSelectedFile] = useState(null);
    const [preview, setPreview] = useState(null);
    const [analyzing, setAnalyzing] = useState(false);
    const [publishing, setPublishing] = useState(false);
    const [aiResult, setAiResult] = useState(null);
    const [error, setError] = useState(null);

    // 處理檔案選擇
    async function handleFileChange(e) {
        const file = e.target.files[0];
        if (!file) return;

        // 檢查檔案類型
        if (!file.type.startsWith('image/')) {
            setError('請選擇圖片檔案');
            return;
        }

        setSelectedFile(file);
        setError(null);

        // 顯示預覽
        const reader = new FileReader();
        reader.onload = (e) => setPreview(e.target.result);
        reader.readAsDataURL(file);

        // 自動開始 AI 分析
        analyzeImage(file);
    }

    // AI 分析圖片
    async function analyzeImage(file) {
        setAnalyzing(true);
        setError(null);

        try {
            // 轉換為 Base64
            const base64 = await fileToBase64(file);

            // 呼叫後端 API (只分析，不上架)
            const response = await callAPI(ApiActions.ANALYZE_ITEM, {
                imageBase64: base64
            });

            if (response.status === 'success') {
                setAiResult(response.data);
            } else {
                setError(response.message || 'AI 分析失敗');
            }
        } catch (err) {
            setError('分析失敗: ' + err.message);
        } finally {
            setAnalyzing(false);
        }
    }

    // 確認上架
    async function handleConfirm(formData) {
        if (!formData) return;

        setPublishing(true);
        setError(null);

        try {
            // 呼叫後端 API (正式上架)
            const response = await callAPI(ApiActions.PUBLISH_ITEM, {
                ...formData,
                id: aiResult.id, // Keep the ID generated by analyzeItem if any, or let backend generate new one if needed (though analyzeItem returns an ID)
                image_url: aiResult.image_url, // Keep the image URL
                sellerId: user?.line_user_id
            });

            if (response.status === 'success') {
                // 成功後導回首頁
                navigate('/');
            } else {
                setError(response.message || '上架失敗');
            }
        } catch (err) {
            setError('上架失敗: ' + err.message);
        } finally {
            setPublishing(false);
        }
    }

    return (
        <div className="min-h-screen bg-gray-50 py-8">
            <div className="container mx-auto px-4 max-w-2xl">
                {/* 標題 */}
                <div className="mb-8">
                    <button
                        onClick={() => navigate('/')}
                        className="text-gray-600 hover:text-gray-800 mb-4 flex items-center gap-2"
                    >
                        ← 返回
                    </button>
                    <h1 className="text-3xl font-bold text-gray-800">上傳制服</h1>
                    <p className="text-gray-600 mt-2">拍攝或選擇制服照片，AI 會自動幫您填寫資訊</p>
                </div>

                {/* 上傳區域 */}
                <div className="bg-white rounded-lg shadow-md p-8">
                    <ProtectedAction>
                        {!selectedFile ? (
                            <div>
                                <label
                                    htmlFor="photo-upload"
                                    className="block w-full"
                                >
                                    <div className="border-4 border-dashed border-gray-300 rounded-lg p-12 text-center cursor-pointer hover:border-blue-500 hover:bg-blue-50 transition-colors">
                                        <svg className="w-16 h-16 mx-auto text-gray-400 mb-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 9a2 2 0 012-2h.93a2 2 0 001.664-.89l.812-1.22A2 2 0 0110.07 4h3.86a2 2 0 011.664.89l.812 1.22A2 2 0 0018.07 7H19a2 2 0 012 2v9a2 2 0 01-2 2H5a2 2 0 01-2-2V9z" />
                                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 13a3 3 0 11-6 0 3 3 0 016 0z" />
                                        </svg>
                                        <p className="text-lg font-semibold text-gray-700 mb-2">點擊上傳或拍照</p>
                                        <p className="text-sm text-gray-500">支援 JPG, PNG 格式</p>
                                    </div>
                                </label>
                                <input
                                    id="photo-upload"
                                    type="file"
                                    accept="image/*"
                                    capture="environment"
                                    onChange={handleFileChange}
                                    className="hidden"
                                />
                            </div>
                        ) : (
                            <div>
                                {/* 圖片預覽 */}
                                <div className="mb-6">
                                    <img
                                        src={preview}
                                        alt="Preview"
                                        className="w-full h-96 object-contain bg-gray-100 rounded-lg"
                                    />
                                    <button
                                        onClick={() => {
                                            setSelectedFile(null);
                                            setPreview(null);
                                            setAiResult(null);
                                            setError(null);
                                        }}
                                        className="mt-4 text-sm text-red-600 hover:text-red-800"
                                    >
                                        重新選擇
                                    </button>
                                </div>

                                {/* AI 分析中 */}
                                {analyzing && (
                                    <div className="text-center py-8">
                                        <div className="inline-block animate-spin rounded-full h-12 w-12 border-4 border-blue-500 border-t-transparent mb-4"></div>
                                        <p className="text-lg font-semibold text-gray-700">AI 正在分析您的制服...</p>
                                        <p className="text-sm text-gray-500 mt-2">請稍候片刻</p>
                                    </div>
                                )}

                                {/* 錯誤訊息 */}
                                {error && (
                                    <div className="bg-red-50 border border-red-200 text-red-800 px-4 py-3 rounded-lg mb-4">
                                        {error}
                                    </div>
                                )}

                                {/* AI 分析結果 (可編輯) */}
                                {aiResult && !analyzing && (
                                    <ItemForm
                                        initialData={aiResult}
                                        onSubmit={handleConfirm}
                                        loading={publishing}
                                        submitLabel="確認並上架"
                                    />
                                )}
                            </div>
                        )}
                    </ProtectedAction>
                </div>
            </div>
        </div>
    );
}
